### ISSUE TITLE
bump mongo version

### ISSUE THREAD

**Issue by ogdonis** [fastify/fastify-mongodb#106]
node version 14.5.x

Warning at runtime:
(node:10928) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

Did not appear in node 12.x:

Fix:
Fix has been made in MongoDB Node.JS Driver
https://jira.mongodb.org/browse/NODE-2536

additional reference
https://developer.mongodb.com/community/forums/t/warning-accessing-non-existent-property-count-of-module-exports-inside-circular-dependency/3183

**Comment by mcollina** [comment]
You can just update your dependencies, the updated version of mongodb will be updated.
