### ISSUE TITLE
Typescript support + option for appending db connection to request object

### ISSUE THREAD

**Issue by gustawdaniel** [fastify/fastify-mongodb#118]
When I type `this.mongo` I see typescript error. I propose to document how to fix it.

I propose also add flag in config that allow for appending connection object to `request` parameter.

https://github.com/fastify/fastify/issues/1417

**Comment by RafaelGSS** [comment]
> When I type `this.mongo` I see typescript error. I propose to document how to fix it.

Can you create a reproducible example? The types seem ok.

**Comment by gustawdaniel** [comment]
Now I see that it could be connected with circular import in my project. I am closing this issue and will reopen If create reproducible example. Thanks.
