### ISSUE TITLE
feat: re-export ObjectId

### ISSUE THREAD

**Issue by climba03003** [fastify/fastify-mongodb#138]
## 🚀 Feature Proposal

It is better to re-export `ObjectId` from `mongodb`. 

## Motivation

Better developer experience.

## Example

It can simplify the use of mongodb API.
For example, when we want to create helper function with `fastify` access.

```js
const { ObjectId } = require('fastify-mongodb')

export function findUserById(collection, id) {
  return collection.findOne({ _id: ObjectId(id) })
}
```

**Comment by mcollina** [comment]
I'm +1

**Comment by iShibi** [comment]
Anyone working on this? If not I can do it

**Comment by climba03003** [comment]
> 
> 
> Anyone working on this? If not I can do it

Feel free to send a Pull Request.
