### ISSUE TITLE
Mongodb connection error

### ISSUE THREAD

**Issue by SudoDios** [fastify/fastify-mongodb#152]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.22.1

### Plugin version

4.1.1

### Node.js version

16.13.0

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04

### Description

Hello.
I launched a clustered **mongodb** and enabled authentication.
But the **fastify-mongodb** plugin does not connect with authentication (**AuthenticationFailed**).
But there is no problem with **MongoClient**. 

### Steps to Reproduce

```javascript
const fastify = require("fastify");
const app = fastify();

app.register(require('fastify-multipart'))
app.register(require('fastify-formbody'))
app.register(require('./FastifyRouter'))

//database
app.register(require('fastify-mongodb'), {
    forceClose: true,
    url: 'mongodb://localhost:27017/db',
    auth: {
        username: "username",
        password: "password"
    }
})

app.listen(port,"hostname",(err,adrs) => {
    if (err) {
        console.log(err)
    } else {
        console.log(address)
    }
})
```

**Comment by Eomm** [comment]
I think you should setup correctly the `url` parameter such as `mongodb://localhost:27017/test?authSource=admin`

**Comment by SudoDios** [comment]
I used this but it did not work :
`mongodb://user:pass@localhost:27017/test`.

You may write a complete url with the parameters. 
(With this new url you mentioned)
(username & password)

**Comment by SudoDios** [comment]
https://github.com/fastify/fastify/discussions/3150

**Comment by SudoDios** [comment]
Do not have a solution?

**Comment by mcollina** [comment]
> Do not have a solution?

I'm afraid no one owes you a solution in any given timeframe.

**Comment by mcollina** [comment]
How do you connect with basic MongoClient?

**Comment by SudoDios** [comment]
> How do you connect with basic MongoClient?

Yes. can connect.
with this url :
`mongodb://user:pass@localhost:27017/test`

**Comment by SudoDios** [comment]
An irrelevant question 🙂: 
Does fastify clustering have an effect at higher speeds ?

**Comment by climba03003** [comment]
> 
> 
> > How do you connect with basic MongoClient?
> 
> Yes. can connect. with this url : `mongodb://user:pass@localhost:27017/test`

From my knowledge of `mongodb`, it means that your account is stored in `test` db?
If that is the case, your connection string with `mongodb://localhost:27017/db` is actually authorizing against `db`.

I think simply pass `mongodb://user:pass@localhost:27017/test` into `url` is fine. The option is directly pass to `MongoClient`, if it can connect in `MongoClient`, it must be able to connect for `fastify-mongodb`.

**Comment by SudoDios** [comment]
I even tested in mongodb compass and authentication was done.  
But not in fastify-mongodb.

**Comment by SudoDios** [comment]
You can also take a test ?

**Comment by climba03003** [comment]
> 
> 
> You can also take a test ?

I always use a single url which contain both `credential`, `host` and `options` to connect the database.
I do not have any problem with it. You can setup a repro with docker to simulate the error.
Or provide the code you are using, which I can connect my database to test it.

**Comment by SudoDios** [comment]
> > 
> > 
> > You can also take a test ?
> 
> I always use a single url which contain both `credential`, `host` and `options` to connect the database.
> I do not have any problem with it. You can setup a repro with docker to simulate the error.
> Or provide the code you are using, which I can connect my database to test it.

Can you write me a complete URL with options?

**Comment by climba03003** [comment]
Note that if you do not specify `database` or `authSource`, `Mongodb Compass` by default using `admin`.

Which is actually ` mongodb://user:pass@localhost:27017/?authSource=admin`

**Comment by SudoDios** [comment]
Thankful.
I will take the test again and report here

**Comment by climba03003** [comment]
Connection String is form like below 
https://docs.mongodb.com/manual/reference/connection-string/#components

mongodb://<username>:<password>@<host>:<port>/[default database]?[<options>]

Note that if `username` or `password` contain `: / ? # [ ] @` please encode your username and password.

**Comment by SudoDios** [comment]
Okey.
thanks

**Comment by SudoDios** [comment]
I tested and authentication was successful 👍. 
 I just had to add the last URL authSource = admin

**Comment by kkkkh** [comment]
> Note that if you do not specify `database` or `authSource`, `Mongodb Compass` by default using `admin`.
> 
> Which is actually ` mongodb://user:pass@localhost:27017/?authSource=admin`
if you want to link a new created db, you must add '?authSource=admin'
I tried ,this is right
