### ISSUE TITLE
Database Selection At Runtime

### ISSUE THREAD

**Issue by akhtar-husain** [fastify/fastify-mongodb#165]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I have a mongodb cluster that has about 40 database that I need to selected based on some criteria. 
Is there a way that I can use to select the database at runtime instead of passing in URI string ?
I have searched over internet and also in the issues & discord but couldn't find any answer.
Any help would be appreciated.

**Comment by Eomm** [comment]
Could you use `fastify.mongo.db(chooseDb(request))`?
https://mongodb.github.io/node-mongodb-native/4.1/classes/Db.html

Or do you have 40 different connections?

**Comment by akhtar-husain** [comment]
Thatnks @Eomm for the quick reply.
I have one connection with 40 different databases.

**Comment by darkgl0w** [comment]
The `fastify-mongodb` [`client` decorator](https://github.com/fastify/fastify-mongodb#reference) should allow you to achieve what you want.

Can you try with something like this ?
```js
const myMongoDb= fastify.mongo.client.db('dbname');
// your code here ...
```

ref.: [Mongo documentation](https://mongodb.github.io/node-mongodb-native/4.1/classes/MongoClient.html)

**Comment by akhtar-husain** [comment]
Thank you @darkgl0w, it worked.
