### ISSUE TITLE
find() method returns events

### ISSUE THREAD

**Issue by damiantoczek** [fastify/fastify-mongodb#166]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.27.1

### Plugin version

4.1.1

### Node.js version

17.3

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Arch Linux latest

### Description

Returns an object with events instead of the actual objects from the database.

### Steps to Reproduce

```js
const app = require('fastify')()

app.register(require('fastify-mongodb', options)

app.get('/test', async function(req,res){
    let collection = this.mongo.db.collection('test')
    let result = await collection.find({});

    return res.send(result)
    // {"_events":{},"_eventsCount":0}
})
```

### Expected Behavior

Should return a result with documents, not events.

**Comment by climba03003** [comment]
Please learn how to use mongodb in the correct [document](https://mongodb.github.io/node-mongodb-native/4.4/classes/Collection.html#find).

`collection.find({})` returns a `cursor` not `data`. It is the correct returns.

**Comment by damiantoczek** [comment]
> Please learn how to use mongodb in the correct [document](https://mongodb.github.io/node-mongodb-native/4.4/classes/Collection.html#find).
> 
> `collection.find({})` returns a `cursor` not `data`. It is the correct returns.

I found this out that I need to use .toArray() to get my data.
