### ISSUE TITLE
Mongodb find({}) error

### ISSUE THREAD

**Issue by kamalbilal** [fastify/fastify-mongodb#191]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

I am using this code 
```
const fastify = require('fastify')()

fastify.register(require('@fastify/mongodb'), {
  // force to close the mongodb connection when app stopped
  // the default value is false
  forceClose: true,
  
  url: 'myDb_URL'
})

fastify.get('/user/:id', function (req, reply) {

  const users = this.mongo.db.collection('users')

  users.findOne({ name: "some name" }, (err, user) => {
    if (err) {
      reply.send(err)
      return
    }
    reply.send(user)
  })
})

fastify.listen({ port: 3000 }, err => {
  if (err) throw err
})
```
By using ``` users.findOne({ name: "some name" })``` I am getting data successfully but when I use ``` users.find({}) ``` to get all the users in ``` users ``` collection it is returning ``` {"statusCode":500,"error":"Internal Server Error","message":"Argument \"options\" must not be function"} ```  

This is my final code and I want to get all the users in ```users``` document.
```
const fastify = require("fastify")();

fastify.register(require("@fastify/mongodb"), {
  // force to close the mongodb connection when app stopped
  // the default value is false
  forceClose: true,

  url: "mongodb://localhost:27017",
});

fastify.get("/", function (req, reply) {
  // Or this.mongo.client.db('mydb').collection('users')
  const users = this.mongo.client.db("Store").collection("offers");

  users.find({}, (err, user) => {
    console.log(err);
    if (err) {
      reply.send(err);
      return;
    }
    console.log(user);
    reply.send(user);
  });
});

fastify.listen({ port: 3000 }, (err) => {
  if (err) throw err;
  console.log("Server running on port 3000");
});
```

**Comment by kamalbilal** [comment]
I am closing this issue, because I found my error.

**Comment by johntom** [comment]
If possible can you share your fix.

**Comment by Eomm** [comment]
The latest mongodb driver 4.9 does not support the callback interface anymore
https://mongodb.github.io/node-mongodb-native/4.9/classes/Collection.html#find

You need to await it:

```
const data = await movies.find(query, options);
```

**Comment by kamalbilal** [comment]
> If possible can you share your fix.

const result = await users.find({}, options)

**Comment by johntom** [comment]
thanks
