### ISSUE TITLE
Enable Dependabot

### ISSUE THREAD

**Issue by mihaur** [fastify/fastify-mongodb#196]
### Issue

It seems dependabot is not enabled for this repository. [dependabot.yml](https://github.com/fastify/fastify-mongodb/blob/master/.github/dependabot.yml) looks ok, run once per week. Maybe it is disabled in the settings.

Last dependabot pull request is #193 from Sep 19.

package.json has some outdate dev dependencies: fastify-plugin@4.0.0 latest is 4.3.0, mongodb@4.0.1 latest is 4.12.0

**Comment by jsumners** [comment]
I'd be interested to see how many Dependabot PRs are actually handled across the org. I'm willing to bet it isn't many, and we should just stop with the bot completely.

**Comment by Uzlopak** [comment]
You mean activate dependabot org wide?

**Comment by jsumners** [comment]
> You mean activate dependabot org wide?

No. My hypothesis is that it should be _removed_ org wide.

**Comment by kibertoad** [comment]
Don't we have automerge workflow for handling Dependabot PRs, which works great?

**Comment by jsumners** [comment]
> Don't we have automerge workflow for handling Dependabot PRs, which works great?

All I can tell you is I see a lot of them show up, are not followed up with by any other automation, and I mute them.

**Comment by Uzlopak** [comment]
We nearly use everywhere our standardized ci-workflow which automatically merges dependabot-PRs. On mondays I basically sip my first coffee of the week and check the PRs for issues. And on good weeks all get merged. Only few typescript projects like fastify-next or fastify-passport have excluded fastify as dependency from autoupdating. 

Also dependabot helps to detect issues in projects, which are not under heavy development. Sometimes a dependabot PR triggers an error in a project, which was long time not touched. E.g. imagine node 19 breaks a project, which had no code change for few months. You get atleast the feedback, that the dependabot-PR didnt run through and invetigate further. 

We usually have no open dependabot PRs.

**Comment by climba03003** [comment]
I am closing this issue, `dependabot` is working for this repo. 
I checked the `Insight` page, the last query for update is `2 days ago`.
