### ISSUE TITLE
Move MongoDB to peerDependencies

### ISSUE THREAD

**Issue by rtritto** [fastify/fastify-mongodb#209]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.14.1

### Plugin version

6.2.0

### Node.js version

16

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

MongoDB should be moved from dependencies to peerDependencies

**Comment by climba03003** [comment]
I am pretty much against the usage of `peerDependencies`.
But open to made changes if others agree.

**Comment by Uzlopak** [comment]
I would prefer to put it into peerDependencies when node14 is deprecated and all supported node versions use npm version >= 7, which ensures that the peerDependencies exist by downloading them. Npm 6 in node 14 does not download the peerDependencies....

**Comment by jsumners** [comment]
Peer dependencies are nothing but trouble. Particularly with the way they keep getting handled differently with seemingly every new npm release.

**Comment by mcollina** [comment]
I'm sincerely -1. They cause more problems than they are worth.

Note that they would not give you any real benefits over a production dependency, because we would not specify a multi-major range.

**Comment by rtritto** [comment]
With no peerDependency, the dependency version can't be chosen (eg: use a specific version in case of bugs).
I think that Fastify plugins should only "connect" and use dependencies where they are installed. Eg: this plugin should have _fastify_ and _mongodb_ as _peerDependencies_, by this way there is a single instance of both and there are no duplicates for installed libraries in dependencies tree.

Some sources:
- [Using peer dependencies](https://www.johno.com/using-peer-dependencies)
- [Understanding peer dependencies in JavaScript](https://blog.bitsrc.io/understanding-peer-dependencies-in-javascript-dbdb4ab5a7be)

**Comment by rtritto** [comment]
@mcollina
> Note that they would not give you any real benefits over a production dependency, because we would not specify a multi-major range.

Eg: having v4 and v5, we have these use cases:
1. minor version:
```js
"peerDependencies": {
  "mongodb": "^4.1.2"  // random version of 4 --> version needed is >= 4.1.2
}
```
2. major version (use only 1 version because they have breaking changes)
```js
"peerDependencies": {
  "mongodb": "^4"  // support only version 4 --> version needed is one of 4
}
```
or
```js
"peerDependencies": {
  "mongodb": "^5"  // support only version 5 --> version needed is one of 5
}
```
3. multiple versions
```js
"peerDependencies": {
  "mongodb": "^4 || ^5"  // support both versions --> version needed is 4 or 5 (handle breaking changes in code if they are needed)
}
```

**Comment by mcollina** [comment]
Maintaining support for multiple versions and handling the breaking changes in the codebase is a (deliberate) non-goal. Maintaining those kind of support matrix is extremely hard, considering all the wrappers there are in this organization. 

All the other three versions have no benefit compared to equivalent versions for normal dependencies. All package managers correctly deduplicate those.

**Comment by rtritto** [comment]
> Maintaining support for multiple versions and handling the breaking changes in the codebase is a (deliberate) non-goal. 

I know, it's advised to update and use only latest (v5).

**Comment by rtritto** [comment]
> All the other three versions have no benefit compared to equivalent versions for normal dependencies. All package managers correctly deduplicate those.

Main problem is with multiple context (instance).

From [Using peer dependencies](https://www.johno.com/using-peer-dependencies):

> Though, more importantly, a peer dependency is more resilient to issues in runtimes. This is particularly important for libraries that use React context like MDX and even Emotion.

> If a library specifies its own version of React/MDX/Emotion/etc. it can end up with multiple versions on the client. This will cause conflicts with React, where context will disappear.

If _peerDependencies_ are used like a standard, there should be less headaches.

**Comment by rtritto** [comment]
> All package managers correctly deduplicate those.

This use case can't be deduped:
```
@fastify/mongodb
----  mongodb 4.2.0-latest
mongodb 4.1.0
```

**Comment by rtritto** [comment]
> All package managers correctly deduplicate those.

This use case can't be deduped:
```
@fastify/mongodb
----  mongodb 4.2.0-latest (dependency of @fastify/mongodb)
mongodb 4.1.0 (same level of @fastify/mongodb)
```

**Comment by mcollina** [comment]
We should not support or facilitate using old and buggy software versions that should not include breaking changes.

In my experience, peer dependencies are a major headache to maintain.

**Comment by rtritto** [comment]
I think that every project is different (unique) and the improvements can be (re)considered.

**Comment by rtritto** [comment]
Is there anyone who can reconsider?
