### ISSUE TITLE
Pass variable to regex fails

### ISSUE THREAD

**Issue by johntom** [fastify/fastify-mongodb#216]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.29.0

### Plugin version

5.0.0

### Node.js version

16.15.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

Windows 10 Home Version 22H2 Build 19045.2846

### Description

1) If I hard code value to regex expression (starting with) function returns expexted data
  ```
async function  policyclifton(yearsearch,policycodesearch) {
       return  policycollection.find({
     "EffectiveYear" :yearsearch,  $and : [ { "Policy Number" : /^CA.*/i } ]
         }).toArray()
   }
```
if I pass a vairable to regex function fails to return data
```
 async function  policyclifton(yearsearch,policycodesearch) {
      return  policycollection.find({
     "EffectiveYear" :yearsearch, 
      $and : [ { "Policy Number" :  "/^" + policycodesearch + "/i" } ] 
     }).toArray() 
   }
```
Collection item
```
{
    "_id" : ObjectId("6451803e3a7ff068cda2ebdf"),
    "Policy Number" : "CA 6675503",
    "EffectiveYear" : 2020
}
```

### Steps to Reproduce

given above

### Expected Behavior

variable pass to regex returns data

**Comment by jsumners** [comment]
You have not constructed your regular expression correctly. The correct way to construct regular expressions with variable substitution is through the `RegExp` function:

```
❯ node
Welcome to Node.js v18.16.0.
Type ".help" for more information.
> var pattern = '[a-z]+'
undefined
> var regex = new RegExp(pattern, 'i')
undefined
> regex.test('foo')
true
>
```

**Comment by johntom** [comment]
Exactly what I needed. Thanks for prompt reply
```
var regex = new RegExp(policycodesearch , 'i')
      return  policycollection.find({
      "EffectiveYear" :yearsearch, 
        $and : [ { "Policy Number" : regex } ] 
     }).toArray()
```

**Comment by climba03003** [comment]
The proper use for `RegExp` in `MongoDB` is

```js
{ $regex: pattern, $options: 'i' }
```

You don't really need extra cost on initialize the `RegExp` object.
See https://www.mongodb.com/docs/manual/reference/operator/query/regex/

**Comment by johntom** [comment]
Thanks , the following works.
```  
async function policyclifton(yearsearch, policycodesearch) {
 // sql "like"  or "contains"
     return policycollection.find({
          "EffectiveYear": yearsearch,
          $and: [{ "Policy Number": { $regex: policycodesearch, $options: '$i' } }]
        }).toArray()
      }
```
```
  async function policyclifton(yearsearch, policycodesearch) {
  // sql starting with   
        return policycollection.find({
             "EffectiveYear": yearsearch,
               $and: [{ "Policy Number":{ $regex : policycodesearch,$options: 'i' } }]
          }).toArray()
}
```
