### ISSUE TITLE
Error Plugin did not start in time: '@fastify/mongodb'. You may have forgotten to call 'done' function or to resolve a Promise

### ISSUE THREAD

**Issue by hoanghiep1x0** [fastify/fastify-mongodb#224]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.x

### Plugin version

^6.0.1

### Node.js version

16.0.9

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

ventura 13.5.2

### Description

Why does connect localhost:27017 work.
but connect to mongo with the address mongodb+srv://user:pass@cluster0.m9frj.mongodb.net/
then get an error 

Plugin file 
```
  'use strict'

  const fp = require('fastify-plugin')
  const fastifyMongo = require('@fastify/mongodb')

  module.exports = fp(async function datasourcePlugin(fastify, opts, next) {

    try {
      fastify.register(fastifyMongo, {
        forceClose: true,
        connectTimeoutMS: 10000,
        url: fastify.secrets.MONGO_URL
      });
    } catch (err) {
      next(err);
    }
  }, {
    dependencies: ['application-config']
  })
```

Plugin did not start in time: '@fastify/mongodb'. You may have forgotten to call 'done' function or to resolve a Promise

### Steps to Reproduce

1. config plugin and run with localhost => work
2. config with mongolab => error

### Expected Behavior

```
Plugin did not start in time: '@fastify/mongodb'. You may have forgotten to call 'done' function or to resolve a Promise
    at Timeout._onTimeout (/Users/admin/Desktop/app/docker/service-data/node_modules/avvio/plugin.js:122:19)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'AVV_ERR_READY_TIMEOUT',
  fn: <ref *1> [AsyncFunction: fastifyMongodb] {
    default: [Circular *1],
    fastifyMongodb: [Circular *1],
    ObjectId: [Function: ObjectId] {
      getInc: [Function (anonymous)],
      generate: [Function (anonymous)],
      createPk: [Function (anonymous)],
      createFromTime: [Function (anonymous)],
      createFromHexString: [Function (anonymous)],
      isValid: [Function (anonymous)],
      fromExtendedJSON: [Function (anonymous)],
      index: 16644978
    },
    [Symbol(skip-override)]: true,
    [Symbol(fastify.display-name)]: '@fastify/mongodb',
    [Symbol(plugin-meta)]: { fastify: '4.x', name: '@fastify/mongodb' }
  }
}
```

**Comment by Uzlopak** [comment]
This indicates that the connection to the db could not be established, as the plugin never resolves.

**Comment by hoanghiep1x0** [comment]
I have configured the db on mongo lap correctly because network open is 0.0.0.0 and user + password is correct. But I don't understand why it doesn't work

**Comment by hoanghiep1x0** [comment]
@Uzlopak But when working on localhost:27017 it runs again, can you help me? I just learned about fastify.

**Comment by climba03003** [comment]
I am closing the issue because there is no indication the problem related to `fastify`.
You can still comment on the issue or seek for helps on the Discord channel.

From my point of view, it clearly you have some connection error to your database, please try the same connection string with `MongoDB Compass` to see if your computer allowed to connect.

**Comment by hoanghiep1x0** [comment]
I am 100% sure the error is from @fastify/mongodb

Here is the code I run perfectly fine with mongoose

const mongoose = require("mongoose");

(async() => {
     try {
         await mongoose.connect('mongodb+srv://demo:demo@cluster0.m9frj.mongodb.net/')
         console.log("connect success");
     } catch (err) {
         console.log(err);
     }
})()

and here is the code that runs with fastify
```
'use strict'

const fp = require('fastify-plugin')
const fastifyMongo = require('@fastify/mongodb')

module.exports = fp(async function databaseConnect(fastify, opts) {
   fastify.register(fastifyMongo, {
     forceClose: true,
     url: 'mongodb+srv://hoanghiep1x0:131312htquynh@cluster0.m9frj.mongodb.net/'
   })
}, {
   dependencies: ['application-config']
})
```

The result is the same as the error I posted

**Comment by hoanghiep1x0** [comment]
tôi chắc chắn 100% lỗi từ @fastify/mongodb

Đây là mã tôi chạy hoàn toàn bình thường với mongoose
```
const mongoose = require("mongoose");

(async () => {
    try {
        await mongoose.connect('mongodb+srv://demo:demo@cluster0.m9frj.mongodb.net/')
        console.log("connect success");
    } catch (err) {
        console.log(err);
    }
})()
```
và đây là mã chạy với fastify
```
'use strict'

const fp = require('fastify-plugin')
const fastifyMongo = require('@fastify/mongodb')

module.exports = fp(async function databaseConnect(fastify, opts) {
  fastify.register(fastifyMongo, {
    forceClose: true,
    url: 'mongodb+srv://demo:demo@cluster0.m9frj.mongodb.net/'
  })
}, {
  dependencies: ['application-config']
})
```

Kết quả nhận được giống lỗi tôi đã đăng

**Comment by Eomm** [comment]
was about to say that in your first code version you are mixin async and next, the latter version of the code should be fine.

I think it may be a firewall or something.
I would suggest to debug it with:

```

module.exports = fp(async function databaseConnect(fastify, opts) {
try{
  await fastify.register(fastifyMongo, {
    forceClose: true,
    url: 'mongodb+srv://demo:demo@cluster0.m9frj.mongodb.net/'
  })
} catch (err) {
console.log(err)
}
}, {
  dependencies: ['application-config']
})

```

**Comment by hoanghiep1x0** [comment]
I still get the same error.
One confusing thing is that it works with localhost:27017

while testing with mongoose new file index.js it works. If it's due to a firewall, mongoose will also not work. Because I am running on the same local machine environment.

**Comment by hoanghiep1x0** [comment]
```
 
 const fp = require('fastify-plugin')
const fastifyMongo = require('@fastify/mongodb')

module.exports = fp(async function databaseConnect(fastify, opts) {
  try {
    await fastify.register(fastifyMongo, {
      forceClose: true,
      url: 'mongodb+srv://demo:demo@cluster0.m9frj.mongodb.net/'
    })
  } catch (err) {
    console.log("ERROR ===>",err)
  }
}, {
  dependencies: ['application-config']
})
```
  
Run -> ERROR ===> AvvioError [Error]: Plugin did not start in time: 'databaseConnect-auto-2'. You may have forgotten to call 'done' function or to resolve a Promise
    at Timeout._onTimeout. :(

**Comment by climba03003** [comment]
I suggest you to try the official package `mongodb`.

```js
import { MongoClient } from 'mongodb'

const client = new MongoClient('mongodb+srv://demo:demo@cluster0.m9frj.mongodb.net/')
await client.connect()
```

**Comment by hoanghiep1x0** [comment]
Thank. I'm just testing to find the problem and fix it.

**Comment by hoanghiep1x0** [comment]
ERROR
```
'use strict'

const fp = require('fastify-plugin')
const fastifyMongo = require('@fastify/mongodb')

module.exports = fp(function datasourcePlugin(fastify, opts, done) {
  fastify.register(fastifyMongo, {
    forceClose: true,
    url: 'mongodb+srv://demo:demo@cluster0.m9frj.mongodb.net/'
  });
  done();
}, {
  name: 'mongodb-plugin',
  dependencies: ['application-config']
})
```

A plugin does not fail

```
'use strict'

const fp = require('fastify-plugin')
const mongoose = require("mongoose");

module.exports = fp(function databaseConnect(fastify, opts, done) {
  mongoose.connect('mongodb+srv://demo:demo@cluster0.m9frj.mongodb.net/').then(() => {
    console.log("connect success");
    return;
  }).catch(err => {
    console.log("ERROR MONGOO CONNECT===>", err);
  })
  done();
}, {
  name: 'plugin-mongoose',
  dependencies: ['application-config']
})
```

**Comment by climba03003** [comment]
You are not doing the same as this plugin, the below is the proper implementation.

```
'use strict'

const fp = require('fastify-plugin')
const mongoose = require("mongoose");

module.exports = fp(function databaseConnect(fastify, opts, done) {
  mongoose.connect('mongodb+srv://demo:demo@cluster0.m9frj.mongodb.net/').then(() => {
    console.log("connect success");
    done();
  }).catch(err => {
    console.log("ERROR MONGOO CONNECT===>", err);
    done(err);
  })
}, {
  name: 'plugin-mongoose',
  dependencies: ['application-config']
})
```

**Comment by hoanghiep1x0** [comment]
> You are not doing the same as this plugin, and you ignore the connection state by resolving the plugin immediately. The below one is waiting for the connection properly.
> 
> ```
> 'use strict'
> 
> const fp = require('fastify-plugin')
> const mongoose = require("mongoose");
> 
> module.exports = fp(function databaseConnect(fastify, opts, done) {
>   mongoose.connect('mongodb+srv://demo:demo@cluster0.m9frj.mongodb.net/').then(() => {
>     console.log("connect success");
>     done();
>   }).catch(err => {
>     console.log("ERROR MONGOO CONNECT===>", err);
>     done(err);
>   })
> }, {
>   name: 'plugin-mongoose',
>   dependencies: ['application-config']
> })
> ```

I tried but doing the above will get an error.

**Comment by climba03003** [comment]
> I tried but doing the above will get an error.

So, you would need to measure how much time you need to connect to the MongoDB Altas.

Increase the [pluginTimeout](https://github.com/fastify/fastify/blob/main/docs/Reference/Server.md#plugintimeout) to 30s or longer.

**Comment by hoanghiep1x0** [comment]
![IMG ERROR](https://i.imgur.com/JHGTDsK.png)

**Comment by hoanghiep1x0** [comment]
What is network classification error and how to fix it. You can specify the way or area to learn how to fix it

**Comment by hoanghiep1x0** [comment]
Thanks I know how to solve the problem maybe this is it. pluginTimeout

**Comment by climba03003** [comment]
The MongoDB Altas connection consist of too many steps.
1. DNS Resolution
2. TCP / IP handshake
3. Authentication

Normally, a connection will be resolved within 1 second. More than 10 second will exist in a slow network.

**Comment by hoanghiep1x0** [comment]
Thank you very much. after fixing with options with pluginTimeout server it is working.

const fastify = Fastify({
  disableRequestLogging: true,
  logger: loggerOptions,
  ajv: {
    customOptions: {
      removeAdditional: 'all'
    }
  },
  connectionTimeout: 60000,
  requestTimeout: 60000,
  pluginTimeout: 90000
})
