### ISSUE TITLE
onClose hook blocking main process

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [fastify/fastify-mongodb#228]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.23.2

### Plugin version

7.0.0

### Node.js version

20.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

13.4

### Description

When calling `fastify.close()` the mongodb plugin blocks the correct exit of the main process, the plugin `onClose` seems not to be resolving anytime. Without registering this plugin the process does not hang undefinitely.

### Steps to Reproduce

- Create simple app with fastify and `@fastify/mongodb` plugin with a mongodb available connection
- Add some graceful shutdown logic like this:

```javascript
process.on('SIGINT', () => {
   fastify.close(() => {
       // never fires
       console.log('done');
  })
  // optional: use wtf-node to see currently hanging tasks: you'll see the pool of connection to your mongodb database
  const timeout = setTimeout(() => {
      clearTimeout(timeout);
      wtf.dump();
    }, 400);
});
```

- Run the process and then press once CTRL + C
- The fastify.close callback will never be fired

### Expected 

- The plugin should tear down correctly the MongoClient instance
- I should not see pool connection when calling wtf.dump() at the end of the process
- The process should close correctly and fastify.close callback should be called

### Workaround

I've found a work around this:

```javascript
// before or after registering @fastify/mongodb:
fastify.addHook('preClose', async () => {
   await fastify.mongo.client.close(true);
})
```

This way the process does not hang anymore and closes correctly. Maybe calling client.close on `onClose`, like the plugin does, is too late?

**Comment by climba03003** [comment]
In your workaround, you are actually `force` closing the mongodb connection which is not the default behavior.
If you need to same behavior, you only need to pass the `forceClose` option.

**Comment by giovanni-bertoncelli** [comment]
I've already tried with that option when registering the plugin but without luck

**Comment by giovanni-bertoncelli** [comment]
Sorry guys, it's probably caused by this: https://github.com/lependu/fastify-nodemailer/issues/107, I'll close this when I'm sure

**Comment by giovanni-bertoncelli** [comment]
BTW that plugin is not maintained anymore but it's still listed in community plugins

**Comment by mcollina** [comment]
Maybe send a PR to drop it from the list!

Can we close this?

**Comment by giovanni-bertoncelli** [comment]
Sure

**Comment by giovanni-bertoncelli** [comment]
@mcollina https://github.com/fastify/fastify/pull/5161 the PR
