### ISSUE TITLE
When does the database disconnect occur？

### ISSUE THREAD

**Issue by jweboy** [fastify/fastify-mongodb#36]
```js
const fastify = require('fastify')()

fastify.register(require('fastify-mongodb'), {
  url: 'mongodb://mongo/mydb'
})

fastify.get('/user/:id', function (req, reply) {
  // Or this.mongo.client.db('mydb')
  const db = this.mongo.db
  db.collection('users', onCollection)

  function onCollection (err, col) {
    if (err) return reply.send(err)

    col.findOne({ id: req.params.id }, (err, user) => {
      reply.send(user)
    })
  }
})

fastify.listen(3000, err => {
  if (err) throw err
})
```

In this code, I did not see ```db.close``` to manually shut down the database. I would like to ask what kind of mechanism is ```fastify-mongodb``` to handle on the database.

**Comment by mcollina** [comment]
fastify offers a fastify.close() method, and a close hook for plugins to use. The connection is closed there.

In the example, close is not called.

**Comment by jweboy** [comment]
Ok, I understand that Fastify's hooks have been solved. Thank you.
