### ISSUE TITLE
Cannot parse databaseName from replicatedDatabase url string

### ISSUE THREAD

**Issue by mirchow** [fastify/fastify-mongodb#44]
When mongodb is replicated, the library fails to properly find and parse databaseName.
There is easier way to parse the databaseName from url string, that properly finds it

Showing a typical production url string with the solution how to parse it properly
```js
const url = mongodb://user1:Passw0rd1@hostname1:27017,hostname2:27017,hostname3:27017/DBNAME?replicaSet=myReplicaSet1&poolSize=25&readPreference=primaryPreferred&appname=myApp
const dbName = /\d{5}\/([^?]*)/g.exec(url)[1]
```
This regex solution would also remove the `url` dependency from this library.
I would recommend to change the code to this logic. I can do a pull request if you are interested.

**Comment by allevo** [comment]
Hi! 
And thank you open this issue.

Can you post the error?

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by mirchow** [comment]
The databaseName gets retrieved as `:27017,hostname2:27017,hostname3/DBNAME` instead of `DBNAME`

The error thrown:

/project/node_modules/mongodb/lib/mongo_client.js:819
            throw err;
            ^
MongoError: database names cannot contain the character '/'
    at Function.MongoError.create (/project/node_modules/mongodb-core/lib/error.js:45:10)
    at validateDatabaseName (/project/node_modules/mongodb/lib/db.js:1644:24)
    at new Db (/project/node_modules/mongodb/lib/db.js:201:3)
    at MongoClient.db (/project/node_modules/mongodb/lib/mongo_client.js:378:12)
    at decorateFastifyInstance (/project/node_modules/fastify-mongodb/index.js:41:23)
    at onConnect (/project/node_modules/fastify-mongodb/index.js:82:5

I'll write some unit tests, and will do a PR for this. Thanks.

**Comment by themre** [comment]
I guess this can be closed?

**Comment by mcollina** [comment]
Thanks!
