### ISSUE TITLE
Async/Await?

### ISSUE THREAD

**Issue by lgertel** [fastify/fastify-mongodb#64]
It's possible to promisify this plugin?

**Comment by danielpdev** [comment]
@lgertel I've made a [sandbox](https://codesandbox.io/s/fastify-async-await-mongodb-zo13f?file=/src/build.js) and there you can see how to use async and await with fastify-mongodb.

@lgertel  can you please close the issue if everything works fine?

**Comment by mcollina** [comment]
example is ok, I’m closing this
