### ISSUE TITLE
fastify.ready() always timeout

### ISSUE THREAD

**Issue by PacoDu** [fastify/fastify-mongodb#65]
When calling the `ready` method from fastify server, mongodb will establish the connection with the mongodb server but it will never return.

```javascript
'use strict'

const app = require('fastify')()

app.register(require('fastify-mongodb'), {
  url: 'mongodb://localhost/user'
})

app.ready(err => {
  if (err) throw err
  console.log('READY')
})
```
This snippet will log READY but it will not exit (if you remove fastify-mongodb registering, it logs READY and return)

I noticed this bug when I was writing `tap` tests, I tried to `await fastify.ready()` in order to test my service decorator, but it always timeout. Adding `forceClose` does not change the behavior of `fastify-mongodb`.

fastify-mongodb: 1.0.0
fastify: 1.13.3

**Comment by PacoDu** [comment]
I took a quick look at `fastify-mongodb` sources but I wasn't able to find the source of this bug as `next` is properly called in every cases.

**Comment by mcollina** [comment]
> This snippet will log READY but it will not exit (if you remove fastify-mongodb registering, it logs READY and return)

That is normal and expected. fastify-mongodb creates a net connection to MongoDB. As such, you have to close it to allow Node.js to shut down normally. You can do that by calling `app.close()`.

**Comment by PacoDu** [comment]
Oh well ... >.< I need to add fastify.close() for my tests to succeed

```javascript
test('mongodb timeout', async t => {
  const app = require('fastify')()
  app.register(require('fastify-mongodb'), {
    url: 'mongodb://localhost/user'
  })

  await app.ready()
  t.strictEqual(typeof app.mongo === 'object', true)
  app.close()
})
```

This took me the all morning to figure this out :'(. I thought that was due to my custom plugins registration.
Could we add this to the documentation ?

**Comment by mcollina** [comment]
Sure, would you mind to send a PR?

**Comment by PacoDu** [comment]
This is due to my lack of expertise with Fastify, I totally missed the close method. But as you said in the related fastify issue this could save a lot of time for someone else in the future 👍 
No problem, I will add a PR for this repository about the connection kept alive.
