### ISSUE TITLE
(examples) Do not throw in async flows

### ISSUE THREAD

**Issue by XVincentX** [fastify/fastify-mongodb#7]
Hey,
I was just having a look to this plugin and, reading the example, I noticed this:

```javascript
fastify.register(require('fastify-mongodb'), {
  url: 'mongodb://mongo/db'
}, err => {
  if (err) throw err
})
```

Throwing in in async flow is an antipattern,  it will probably crash your entire process as nobody can catch that exception. While it's just an example, you might want to write a different code to handle the error.

P.S: The same goes in the `listen` function below.

**Comment by delvedor** [comment]
Throw in that callback will crash your process :)
The error handling is demanded to the user, it is your choice how handle it.

**Comment by XVincentX** [comment]
> The error handling is demanded to the user, it is your choice how handle it.

I know, I was just thinking that's is wrong to put it there; a good `console.error` in case of any error would probably be better, but it's your call.

**Comment by delvedor** [comment]
It definitely depends on your code, for example, you have a web service that needs mongodb, without it cannot work.
What you do is try to connect to mongo with this plugin and if you can't, throw an error.

Don't forget that the callback is executed at bootstrap time, so if it have to crash, it will do it when you open up the server, not at "runtime" :)

**Comment by XVincentX** [comment]
Al right, I got your point.

**Comment by mcollina** [comment]
The correct approach is **not** to place any callback there. The default behavior in case of error is well defined (it will emit an `'error'` event on the server). We just need to update the README.

Placing `console.error(err)` there are wrong in both cases, as those are fatal and not-recoverable errors for the demo script.
