### ISSUE TITLE
How to get reference of fastify instance from a standalone route handler?

### ISSUE THREAD

**Issue by amio** [fastify/fastify-mongodb#9]
How should I get the reference to `fastify` in this standalone route handler?

handler.js:
```js
module.exports = (req, reply) => {
  const { db } = fastify.mongo // how should I get this `fastify`?
  db.collection('users', onCollection)

  function onCollection (err, col) {
    if (err) return reply.send(err)

    col.findOne({ id: req.params.id }, (err, user) => {
      reply.send(user)
    })
  })
}
```

index.js:
```javascript
const fastify = require('fastify')
const handler = require('./handler.js')

fastify.register(require('fastify-mongodb'), { url: 'mongodb://mongo/db' })

fastify.get('/user/:id', handler)

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})
```

**Comment by StarpTech** [comment]
@amio that's depends on your structure.

This would solve it.

```js
module.exports = (fastify) => {
return (req, reply) => {
  const { db } = fastify.mongo // how should I get this `fastify`?
  }
}

fastify.get('/user/:id', require('./handler')(fastify))
```
but @delvedor I recommend to decorate the `request` object with the mongo instance.

**Comment by delvedor** [comment]
Hi @amio, thanks for checking out the project!
I highly recommend to use plugins, they are zero cost abstraction that will easily solve your problem.
Furthermore you can use this technique everywhere in you application, is very flexible. There is no need to invent some complex closure structure to get all your stuff :)

```js
const fastify = require('fastify')
const handler = require('./handler.js')

fastify.register(require('fastify-mongodb'), { url: 'mongodb://mongo/db' })
fastify.register(require('./route'))

fastify.listen(3000, err => {
  if (err) throw err
  console.log(`server listening on ${fastify.server.address().port}`)
})
```
```js
module.exports = function route (fastify, opts, next) {
  const { db } = fastify.mongo
  const usersCol = db.collection('users')

  fastify.get('/user/:id', (req, reply) => {
    usersCol.findOne(
      { id: req.params.id },
      onFind
    )

    function onFind (err, user) {
      reply.send(err || user)
    }
  })

  next()
}
```

**Comment by StarpTech** [comment]
yes, that's definitely the way to go, I thought you solve it without plugins

**Comment by amio** [comment]
Thanks for your replies!

I was trying to write a plugin for mongorito, hoping to share the db reference across handlers. Decorating the `request` object could solve this, but I'm not sure is it a recommended way for such use case.

**Comment by delvedor** [comment]
You can decorate the request object, but I don't think is a good idea.
You are adding the entire database instance to every request, the memory footprint of your application will increase a lot.

If I may, why do you need to register the handlers externally?
If you really need it, wrap the fastify instance with a closure probably is better.

**Comment by amio** [comment]
Registering handlers externally is mainly for limit file length (e.g. less than 300 lines)

By "wrap fastify instance with a closure" did you mean making every route a plugin?
```js
module.exports = function routeUsers (fastify, opts, next) {
  const { db } = fastify.mongo

  fastify.get('/user/:id', (req, reply) => {
    // ...
  })

  next()
}
```

or exporting a factory function for route handler?
```js
// handler-users.js
module.exports = function routeUsers (fastify) {
  const { db } = fastify.mongo

  fastify.get('/user/:id', (req, reply) => {
    // ...
  })

  next()
}

// routes.js
const users = require('./handler-users.js')
const books = require('./handler-books.js')

module.exports = function route (fastify, opts, next) {

  fastify.get('/user/:id', users(fastify))
  fastify.get('/book/:id', books(fastify))
  // ...

  next()
}
```

**Comment by delvedor** [comment]
I meant the second approach you wrote.
But again, it not a good idea, you are not saving so much lines to justify the effort to create closures and so on. The plugin technique is very flexible and completely avoid the closure problem. Furthermore you can also use [route prefix](https://github.com/fastify/fastify/blob/master/docs/Routes.md#route-prefixing), that is a useful feature :)

**Comment by amio** [comment]
Thanks! I prefer the 2nd method too, and neither thought it's the best approach.

But I'm not sure if I get the right point, how to write a plugin to support this use case? If I do want to keep route handlers in separated files.

**Comment by mcollina** [comment]
If you split the route definition from the handler, you are losing a critical information in your js file: which route your are handling. You need to open two files to understand the structure of your code.

You can do:

```js
// users.js
module.exports = function users (fastify, opts, next) {
  const { db } = fastify.mongo

  fastify.get('/:id', (req, reply) => {
    // ...
  })

  next()
}
```

```js
module.exports = function app (fastify, opts, next) {

  fastify.register(require('./users'), { prefix: '/users' })
  fastify.register(require('./books'), { prefix: '/books' })
  // ...

  next()
}
```

**Comment by arumugasundar** [comment]
Hi,
As a newbie, I faced a similar kind of hiccup today. Below solution works for me. Happy to get suggestions on whether this approach is good to go with . . .
   
### **index.js**
  ```
 import Fastify from 'fastify';
import fastifyMongodb from '@fastify/mongodb';
import { routesConfig }  from './routes.js';

const fastify = Fastify({
  logger: true
})

fastify.register(fastifyMongodb, {
    forceClose: true,
    url: '<mongodb_url>'
})

routesConfig.forEach((route) => {
    fastify.route(route)
})

try {
  await fastify.listen({ port: 3000 })
} catch (err) {
  fastify.log.error(err)
  process.exit(1)
}
```

### **routes.js**
```
import { <handler_function> } from "./controllers.js";

export const routesConfig = [
    {
        method: 'GET',
        url: '/<path>',
        handler: <handler_function>
    }
];
```

### **controllers.js**
```
export const <handler_function> = async (req,reply) => {
    const mongo = req.server.mongo
    const collection = mongo.client.db('<db_name>').collection('<collection_name>')
    try {
        const res = await collection.find({}) // to be replaced with needed logic
        return reply.send(res)
    } catch (err) {
        return reply.send(err)
    }
}
```
   
   Thanks!

**Comment by melroy89** [comment]
> As a newbie, I faced a similar kind of hiccup today. Below solution works for me. Happy to get suggestions on whether this approach is good to go with . . .

Yes, I believe what you do is also fine. Because just relativity recently the instance is now also part of `req`: https://github.com/fastify/fastify/pull/3102
