### ISSUE TITLE
How to get mongo db in onReady hook?

### ISSUE THREAD

**Issue by gustawdaniel** [fastify/fastify-mongodb#97]
For example:

```
fastify.mongo 
```

is defined, but `fastify.mongo.db` is undefined.

How can I wait for mongo connection?

**Comment by StarpTech** [comment]
It's impossible to help you with such an issue description. Please provide a full example.

**Comment by kibertoad** [comment]
Please provide options that you are passing. Likely 'database' is missing.

**Comment by gustawdaniel** [comment]
I had invalid mongo url. Sorry for this question.
